package com.grapheople.domain.user.enums;

public enum Country {
    REPUBLIC_OF_KOREA,
    UNITED_STATES,
    JAPAN,
    CHINA,
    TAIWAN,
    HONG_KONG,
    SINGAPORE,
    VIETNAM,
    THAILAND,
    MALAYSIA,
    INDONESIA,
    PHILIPPINES,
    INDIA,
    AUSTRALIA,
    NEW_ZEALAND,
    UNITED_KINGDOM,
    FRANCE,
    GERMANY,
    ITALY,
    SPAIN,
    RUSSIA,
    CANADA,
    MEXICO,
    BRAZIL,
    ARGENTINA,
    SOUTH_AFRICA,
    EGYPT,
    NIGERIA,
    KENYA,
    TURKEY,
    SAUDI_ARABIA,
    UNITED_ARAB_EMIRATES,
    OTHER,
}
