### 운동 조회
GET {{host}}/api/v1/workouts/1

### 운동 생성
POST {{host}}/api/v1/workouts
Content-Type: application/json

{
  "name": "Test workout",
  "workoutType": "CYCLING"
}

### 운동 기록 생성
POST {{host}}/api/v1/workout-logs
Content-Type: application/json

{
  "uuid": "eeb2f3e5-c252-3f64-9486-c35c6bd9a7e8",
  "workoutId": 2001,
  "workoutName": "Cycling Morning Ride",
  "durationSec": 3600,
  "distanceMeter": 25000,
  "calorie": 750,
  "exp": 120,
  "exerciseAt": "2025-10-02T06:30:00Z",
  "exerciseDate": "2025-10-02",
  "startAt": "2025-10-02T06:30:00",
  "endAt": "2025-10-02T07:30:00"
}

### 운동 기록 조회
GET {{host}}/api/v1/workout-logs/1
Content-Type: application/json